version: '3.8'
services:
  auth-db:
    image: postgres:14-alpine
    container_name: auth-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kittykat
      POSTGRES_DB: lockbox-auth